service:
  crawler:
    image: jtw7913/kkuko-unofficial-api:crawler
    container_name: kkuko-crawler
    restart: unless-stopped
    env_file:
      - .env.prod
    networks:
      - internal

networks:
  internal:
    name: internal-network
    driver: bridge